export const degreeTypes = {
  BACHELOR: 'Bachelor',
  MASTER: 'Master',
  ASSOCIATE: 'Associate',
  MBA: 'MBA',
  DOCTORATE: 'Doctorate',
  OTHER: 'Other',
};

export const fieldOfStudyTypes = {
  // Engineering
  ELECTRICAL_ENGINEERING: 'Electrical Engineering',
  MECHANICAL_ENGINEERING: 'Mechanical Engineering',
  CIVIL_ENGINEERING: 'Civil Engineering',
  COMPUTER_ENGINEERING: 'Computer Engineering',
  CHEMICAL_ENGINEERING: 'Chemical Engineering',
  AEROSPACE_ENGINEERING: 'Aerospace Engineering',
  BIOMEDICAL_ENGINEERING: 'Biomedical Engineering',
  ENVIRONMENTAL_ENGINEERING: 'Environmental Engineering',
  INDUSTRIAL_ENGINEERING: 'Industrial Engineering',
  MATERIALS_SCIENCE_ENGINEERING: 'Materials Science Engineering',
  NUCLEAR_ENGINEERING: 'Nuclear Engineering',
  PETROLEUM_ENGINEERING: 'Petroleum Engineering',
  SOFTWARE_ENGINEERING: 'Software Engineering',

  // Medicine and Health Sciences
  GENERAL_MEDICINE: 'General Medicine',
  DENTISTRY: 'Dentistry',
  NURSING: 'Nursing',
  PHARMACY: 'Pharmacy',
  PUBLIC_HEALTH: 'Public Health',
  VETERINARY_MEDICINE: 'Veterinary Medicine',
  PHYSICAL_THERAPY: 'Physical Therapy',
  OCCUPATIONAL_THERAPY: 'Occupational Therapy',
  NUTRITION_AND_DIETETICS: 'Nutrition and Dietetics',
  MEDICAL_LABORATORY_SCIENCE: 'Medical Laboratory Science',
  OPTOMETRY: 'Optometry',
  RADIOLOGIC_TECHNOLOGY: 'Radiologic Technology',

  // Business and Management
  BUSINESS_ADMINISTRATION: 'Business Administration',
  ACCOUNTING: 'Accounting',
  MARKETING: 'Marketing',
  FINANCE: 'Finance',
  HUMAN_RESOURCE_MANAGEMENT: 'Human Resource Management',
  INTERNATIONAL_BUSINESS: 'International Business',
  ENTREPRENEURSHIP: 'Entrepreneurship',
  SUPPLY_CHAIN_MANAGEMENT: 'Supply Chain Management',
  HOSPITALITY_MANAGEMENT: 'Hospitality Management',

  // Natural Sciences
  BIOLOGY: 'Biology',
  CHEMISTRY: 'Chemistry',
  PHYSICS: 'Physics',
  ASTRONOMY: 'Astronomy',
  EARTH_SCIENCES: 'Earth Sciences',
  ENVIRONMENTAL_SCIENCE: 'Environmental Science',
  MARINE_BIOLOGY: 'Marine Biology',
  GENETICS: 'Genetics',
  MICROBIOLOGY: 'Microbiology',
  BIOCHEMISTRY: 'Biochemistry',

  // Mathematics and Statistics
  MATHEMATICS: 'Mathematics',
  STATISTICS: 'Statistics',
  APPLIED_MATHEMATICS: 'Applied Mathematics',
  ACTUARIAL_SCIENCE: 'Actuarial Science',
  DATA_SCIENCE: 'Data Science',

  // Computer and Information Sciences
  COMPUTER_SCIENCE: 'Computer Science',
  INFORMATION_TECHNOLOGY: 'Information Technology',
  CYBERSECURITY: 'Cybersecurity',
  ARTIFICIAL_INTELLIGENCE: 'Artificial Intelligence',
  BIOINFORMATICS: 'Bioinformatics',

  // Humanities
  LITERATURE: 'Literature',
  HISTORY: 'History',
  PHILOSOPHY: 'Philosophy',
  LINGUISTICS: 'Linguistics',
  RELIGIOUS_STUDIES: 'Religious Studies',
  CLASSICAL_STUDIES: 'Classical Studies',
  COMPARATIVE_LITERATURE: 'Comparative Literature',

  // Social Sciences
  PSYCHOLOGY: 'Psychology',
  SOCIOLOGY: 'Sociology',
  POLITICAL_SCIENCE: 'Political Science',
  ANTHROPOLOGY: 'Anthropology',
  ARCHAEOLOGY: 'Archaeology',
  ECONOMICS: 'Economics',
  GEOGRAPHY: 'Geography',
  INTERNATIONAL_RELATIONS: 'International Relations',
  SOCIAL_WORK: 'Social Work',
  CRIMINOLOGY: 'Criminology',

  // Law and Legal Studies
  LAW: 'Law',
  INTERNATIONAL_LAW: 'International Law',
  CRIMINAL_JUSTICE: 'Criminal Justice',
  LEGAL_STUDIES: 'Legal Studies',

  // Education
  EDUCATION: 'Education',
  SPECIAL_EDUCATION: 'Special Education',
  EARLY_CHILDHOOD_EDUCATION: 'Early Childhood Education',
  EDUCATIONAL_PSYCHOLOGY: 'Educational Psychology',
  CURRICULUM_AND_INSTRUCTION: 'Curriculum and Instruction',

  // Arts and Design
  ART: 'Art',
  MUSIC: 'Music',
  THEATER: 'Theater',
  FINE_ARTS: 'Fine Arts',
  GRAPHIC_DESIGN: 'Graphic Design',
  INDUSTRIAL_DESIGN: 'Industrial Design',
  FASHION_DESIGN: 'Fashion Design',
  INTERIOR_DESIGN: 'Interior Design',
  ARCHITECTURE: 'Architecture',
  FILM_AND_MEDIA_STUDIES: 'Film and Media Studies',

  // Communication and Journalism
  COMMUNICATION_STUDIES: 'Communication Studies',
  JOURNALISM: 'Journalism',
  PUBLIC_RELATIONS: 'Public Relations',
  ADVERTISING: 'Advertising',
  DIGITAL_MEDIA: 'Digital Media',

  // Agriculture and Environmental Studies
  AGRICULTURAL_SCIENCE: 'Agricultural Science',
  FORESTRY: 'Forestry',
  HORTICULTURE: 'Horticulture',
  WILDLIFE_AND_FISHERIES: 'Wildlife and Fisheries',
  SUSTAINABLE_DEVELOPMENT: 'Sustainable Development',

  // Interdisciplinary Studies
  COGNITIVE_SCIENCE: 'Cognitive Science',
  NEUROSCIENCE: 'Neuroscience',
  GENDER_STUDIES: 'Gender Studies',
  ENVIRONMENTAL_STUDIES: 'Environmental Studies',
  GLOBAL_STUDIES: 'Global Studies',

  OTHER: 'Other',
};

export const genderTypes = {
  MALE: 'male',
  FEMALE: 'female',
};

export const salaryTypes = {
  PER_HOUR: 'hourly',
  PER_DAY: 'daily',
  PER_WEEK: 'weekly',
  PER_MONTH: 'monthly',
  PER_YEAR: 'yearly',
};

export const skillTypes = {
  // Programming Languages
  JAVA: 'Java',
  PYTHON: 'Python',
  C: 'C',
  C_SHARP: 'C#',
  C_PLUS_PLUS: 'C++',
  JAVASCRIPT: 'Javascript',
  TYPESCRIPT: 'Typescript',
  RUBY: 'Ruby',
  PHP: 'PHP',
  SWIFT: 'Swift',
  KOTLIN: 'Kotlin',
  GO: 'Go',
  RUST: 'Rust',
  SCALA: 'Scala',
  PERL: 'Perl',
  R: 'R',
  MATLAB: 'MATLAB',
  DART: 'Dart',
  GROOVY: 'Groovy',
  HASKELL: 'Haskell',
  LUA: 'Lua',
  OBJECTIVE_C: 'Objective-C',
  ASSEMBLY: 'Assembly',
  FORTRAN: 'Fortran',
  COBOL: 'COBOL',
  LISP: 'Lisp',
  PROLOG: 'Prolog',
  ERLANG: 'Erlang',
  CLOJURE: 'Clojure',
  F_SHARP: 'F#',
  OCAML: 'OCaml',
  JULIA: 'Julia',
  RACKET: 'Racket',
  CRYSTAL: 'Crystal',
  ELIXIR: 'Elixir',
  VISUAL_BASIC: 'Visual Basic',
  VHDL: 'VHDL',
  VERILOG: 'Verilog',
  ADA: 'Ada',
  PASCAL: 'Pascal',
  PL_SQL: 'PL/SQL',
  SHELL_SCRIPT: 'Shell Script',
  POWERSHELL: 'PowerShell',
  TCL: 'Tcl',

  // Web Technologies
  HTML: 'HTML',
  CSS: 'CSS',
  XML: 'XML',
  JSON: 'JSON',
  GRAPHQL: 'GraphQL',
  WEBSOCKET: 'WebSocket',
  WEBASSEMBLY: 'WebAssembly',

  // Frameworks and Libraries
  REACT: 'React',
  ANGULAR: 'Angular',
  VUE: 'Vue',
  SVELTE: 'Svelte',
  JQUERY: 'jQuery',
  BACKBONE: 'Backbone.js',
  EMBER: 'Ember.js',
  METEORJS: 'Meteor.js',
  EXPRESSJS: 'Express.js',
  NEXTJS: 'Next.js',
  NUXTJS: 'Nuxt.js',
  GATSBYJS: 'Gatsby.js',
  SPRING: 'Spring',
  SPRING_BOOT: 'Spring Boot',
  HIBERNATE: 'Hibernate',
  STRUTS: 'Struts',
  DJANGO: 'Django',
  FLASK: 'Flask',
  FASTAPI: 'FastAPI',
  PYRAMID: 'Pyramid',
  ASP_NET: 'ASP.NET',
  ASP_NET_CORE: 'ASP.NET Core',
  RUBY_ON_RAILS: 'Ruby on Rails',
  SINATRA: 'Sinatra',
  LARAVEL: 'Laravel',
  SYMFONY: 'Symfony',
  CODEIGNITER: 'CodeIgniter',
  CAKEPHP: 'CakePHP',
  YII: 'Yii',
  ZEND: 'Zend Framework',
  NODEJS: 'Node.js',
  DENO: 'Deno',
  FLUTTER: 'Flutter',
  REACT_NATIVE: 'React Native',
  XAMARIN: 'Xamarin',
  IONIC: 'Ionic',
  ELECTRON: 'Electron',
  QT: 'Qt',
  GTK: 'GTK',
  WORDPRESS: 'WordPress',
  DRUPAL: 'Drupal',
  JOOMLA: 'Joomla',
  MAGENTO: 'Magento',
  SVELTEKIT: 'SvelteKit',

  // Databases
  SQL: 'SQL',
  MYSQL: 'MySQL',
  POSTGRESQL: 'PostgreSQL',
  ORACLE: 'Oracle',
  MONGODB: 'MongoDB',
  CASSANDRA: 'Cassandra',
  REDIS: 'Redis',
  COUCHDB: 'CouchDB',
  NEO4J: 'Neo4j',
  ELASTICSEARCH: 'Elasticsearch',
  SNOWFLAKE: 'Snowflake',
  DYNAMODB: 'DynamoDB',
  BIGQUERY: 'BigQuery',
  HIVE: 'Hive',
  SPANNER: 'Google Spanner',
  MSSQL: 'Microsoft SQL Server',
  FIREBASE: 'Firebase',

  // SAP Technologies
  SAP: 'SAP',
  SAP_HANA: 'SAP HANA',
  SAP_ABAP: 'SAP ABAP',
  SAP_BW: 'SAP BW',
  SAP_FI: 'SAP FI',
  SAP_CO: 'SAP CO',
  SAP_SD: 'SAP SD',
  SAP_MM: 'SAP MM',
  SAP_PP: 'SAP PP',
  SAP_HR: 'SAP HR',
  SAP_S4HANA: 'SAP S/4HANA',
  SAP_FIORI: 'SAP Fiori',
  SAP_NETWEAVER: 'SAP NetWeaver',
  SAP_BUSINESS_ONE: 'SAP Business One',
  SAP_ARIBA: 'SAP Ariba',
  SAP_SUCCESSFACTORS: 'SAP SuccessFactors',
  SAP_CONCUR: 'SAP Concur',
  SAP_CLOUD_PLATFORM: 'SAP Cloud Platform',

  // DevOps and Cloud
  GIT: 'Git',
  DOCKER: 'Docker',
  KUBERNETES: 'Kubernetes',
  JENKINS: 'Jenkins',
  TRAVIS_CI: 'Travis CI',
  CIRCLECI: 'CircleCI',
  ANSIBLE: 'Ansible',
  PUPPET: 'Puppet',
  CHEF: 'Chef',
  TERRAFORM: 'Terraform',
  AWS: 'AWS',
  AZURE: 'Azure',
  GOOGLE_CLOUD: 'Google Cloud',
  HEROKU: 'Heroku',
  DIGITALOCEAN: 'DigitalOcean',
  OPENSTACK: 'OpenStack',
  VAGRANT: 'Vagrant',
  DEVOPS: 'DevOps',
  GRAFANA: 'Grafana',
  PROMETHEUS: 'Prometheus',
  SPLUNK: 'Splunk',
  ELK_STACK: 'ELK Stack (Elasticsearch, Logstash, Kibana)',

  // Data Science and AI
  MACHINE_LEARNING: 'Machine Learning',
  DEEP_LEARNING: 'Deep Learning',
  DATA_SCIENCE: 'Data Science',
  TENSORFLOW: 'TensorFlow',
  PYTORCH: 'PyTorch',
  KERAS: 'Keras',
  SCIKIT_LEARN: 'Scikit-learn',
  PANDAS: 'Pandas',
  NUMPY: 'NumPy',
  MATPLOTLIB: 'Matplotlib',
  SEABORN: 'Seaborn',
  PLOTLY: 'Plotly',
  STATS_MODELS: 'StatsModels',
  OPEN_CV: 'OpenCV',
  PYGAME: 'Pygame',
  REQUESTS: 'Requests',
  SCRAPY: 'Scrapy',
  SQLALCHEMY: 'SQLAlchemy',
  PYMONGO: 'PyMongo',
  DASK: 'Dask',
  SAS: 'SAS',
  SPARK: 'Apache Spark',
  HADOOP: 'Hadoop',

  // IT Computer Science
  ALGORITHMS: 'Algorithms',
  DATA_STRUCTURES: 'Data Structures',
  OPERATING_SYSTEMS: 'Operating Systems',
  DATABASE_MANAGEMENT: 'Database Management',
  COMPUTER_ARCHITECTURE: 'Computer Architecture',
  ARTIFICIAL_INTELLIGENCE: 'Artificial Intelligence',
  COMPUTER_NETWORKS: 'Computer Networks',
  CYBERSECURITY: 'Cybersecurity',
  CRYPTOGRAPHY: 'Cryptography',
  DISTRIBUTED_SYSTEMS: 'Distributed Systems',
  HIGH_PERFORMANCE_COMPUTING: 'High-Performance Computing',
  QUANTUM_COMPUTING: 'Quantum Computing',

  // Networking
  NETWORK_SECURITY: 'Network Security',
  CISCO_NETWORKING: 'Cisco Networking',
  NETWORK_PROTOCOLS: 'Network Protocols',
  WIRELESS_NETWORKING: 'Wireless Networking',
  CLOUD_NETWORKING: 'Cloud Networking',
  VPN: 'VPN',
  SDN: 'Software-Defined Networking',
  VOIP: 'VoIP',

  // Project Management
  AGILE: 'Agile',
  SCRUM: 'Scrum',
  KANBAN: 'Kanban',
  PRINCE2: 'PRINCE2',
  SIX_SIGMA: 'Six Sigma',
  PMP: 'Project Management Professional (PMP)',
  LEAN: 'Lean',
  WATERFALL: 'Waterfall',
  ITIL: 'ITIL',

  COLD_CALL: 'Cold Call',
  CUSTOMER_SERVICE: 'Customer Service',

  // AWS Services
  AWS_EC2: 'AWS EC2',
  AWS_S3: 'AWS S3',
  AWS_RDS: 'AWS RDS',
  AWS_LAMBDA: 'AWS Lambda',
  AWS_CLOUDWATCH: 'AWS CloudWatch',
  AWS_DYNAMODB: 'AWS DynamoDB',
  AWS_SQS: 'AWS SQS',
  AWS_KINESIS: 'AWS Kinesis',
  AWS_GLUE: 'AWS Glue',
  AWS_API_GATEWAY: 'AWS API Gateway',
  AWS_ELASTIC_BEANSTALK: 'AWS Elastic Beanstalk',
  AWS_VPC: 'AWS VPC',
  AWS_IAM: 'AWS IAM',
  AWS_ROUTE_53: 'AWS Route 53',
  AWS_REDSHIFT: 'AWS Redshift',
  AWS_FARGATE: 'AWS Fargate',
  AWS_ELASTICSEARCH: 'AWS Elasticsearch',

  // Servers and Virtualization
  LINUX_SERVER: 'Linux Server',
  WINDOWS_SERVER: 'Windows Server',
  APACHE: 'Apache',
  NGINX: 'Nginx',
  TOMCAT: 'Tomcat',
  JBOSS: 'JBoss',
  IIS: 'IIS (Internet Information Services)',
  VIRTUALBOX: 'VirtualBox',
  VMWARE: 'VMware',
  KVM: 'KVM',
  PROXMOX: 'Proxmox',

  GOOGLE_ANALYTIC: 'Google Analytic',
  TABLEAU: 'Tableau',
  THOUGHTSPOT: 'Thoughtspot',
  POWERBI: 'PowerBI',
  ANALYTICS: 'Analytics',
  RESTAPI: 'REST API',
  KUBEFLOW: 'Kubeflow',
};

export const specializationTypes = {
  ACCOUNTING: 'Accounting',
  BUSINESS: 'Business',
  DEVELOPMENT: 'Development',
  ECONOMICS: 'Economics',
  ENGINEERING: 'Engineering',
  HEALTH: 'Health',
  MARKETING: 'Marketing',
  OPERATIONS: 'Operations',
  FINANCE: 'Finance',
  HUMAN_RESOURCES: 'Human Resources',
  INFORMATION_TECHNOLOGY: 'Information Technology',
  FRONTEND_DEVELOPMENT: 'Frontend Development',
  BACKEND_DEVELOPMENT: 'Backend Development',
  FULLSTACK_DEVELOPMENT: 'Fullstack Development',
  MOBILE_DEVELOPMENT: 'Mobile Development',
  DEVOPS: 'DevOps',
  CLOUD_COMPUTING: 'Cloud Computing',
  DATA_SCIENCE: 'Data Science',
  MACHINE_LEARNING: 'Machine Learning',
  ARTIFICIAL_INTELLIGENCE: 'Artificial Intelligence',
  CYBER_SECURITY: 'Cyber Security',
  DATABASE_ADMINISTRATION: 'Database Administration',
  NETWORK_ENGINEERING: 'Network Engineering',
  SYSTEM_ADMINISTRATION: 'System Administration',
  SOFTWARE_TESTING: 'Software Testing',
  UX_UI_DESIGN: 'UX/UI Design',
  GAME_DEVELOPMENT: 'Game Development',
  ROBOTICS: 'Robotics',
  BLOCKCHAIN: 'Blockchain',
  IOT: 'Internet of Things (IoT)',
  EDUCATION: 'Education',
  LAW: 'Law',
  ART: 'Art',
  DESIGN: 'Design',
  PSYCHOLOGY: 'Psychology',
  SOCIAL_SCIENCES: 'Social Sciences',
  ENVIRONMENTAL_SCIENCE: 'Environmental Science',
  COMMUNICATIONS: 'Communications',
  MEDIA: 'Media',
  PUBLIC_RELATIONS: 'Public Relations',
  SALES: 'Sales',
  PROJECT_MANAGEMENT: 'Project Management',
  SUPPLY_CHAIN_MANAGEMENT: 'Supply Chain Management',
  OTHER: 'Other',
};

export const jobTypes = {
  FULL_TIME: 'Full-Time',
  PART_TIME: 'Part-Time',
  CONTRACT: 'Contract',
  INTERNSHIP: 'Internship',
  OTHER: 'Other',
};

export const workModeTypes = {
  ONSITE: 'Onsite',
  HYBRID: 'Hybrid',
  REMOTE: 'Remote',
  OTHER: 'Other',
};

export const applicationStatusTypes = {
  APPLIED: 'Applied',
  SHORTLISTED: 'Shortlisted',
  INTERVIEW: 'Interview',
  SKILL_TEST: 'Skill Test',
  OFFER: 'Offer',
  HIRED: 'Hired',
  REJECTED: 'Rejected',
};

export const LastUpdateRanges = {
  pastMonth: { $gte: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000) },
  pastWeek: { $gte: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000) },
  past24Hours: { $gte: new Date(Date.now() - 24 * 60 * 60 * 1000) },
};

export const jobStatus = {
  OPEN: 'open',
  PAUSED: 'paused',
  EXPIRED: 'expired',
  DRAFT: 'drafted',
};

export const questionType = {
  EDUCATION: 'Education',
  EXPERIENCE: 'Experience',
  LOCATION: 'Location',
  SALARY_EXPECTATION: 'Salary expectation',
  ABILITY_TO_COMMUTE: 'Ability to commute/relocate',
  LANGUAGE: 'Language',
  LICENSE_CERTIFICATION: 'License/Certification',
  CUSTOM: 'Custom',
};

export const jobTitleTypes = {
  // Software Development
  FRONTEND_DEVELOPER: 'Frontend Developer',
  BACKEND_DEVELOPER: 'Backend Developer',
  FULLSTACK_DEVELOPER: 'Fullstack Developer',
  MOBILE_APP_DEVELOPER: 'Mobile App Developer',
  IOS_DEVELOPER: 'iOS Developer',
  ANDROID_DEVELOPER: 'Android Developer',
  SOFTWARE_ENGINEER: 'Software Engineer',
  SENIOR_SOFTWARE_ENGINEER: 'Senior Software Engineer',
  LEAD_SOFTWARE_ENGINEER: 'Lead Software Engineer',
  PRINCIPAL_SOFTWARE_ENGINEER: 'Principal Software Engineer',
  SOFTWARE_ARCHITECT: 'Software Architect',
  DEVOPS_ENGINEER: 'DevOps Engineer',
  SITE_RELIABILITY_ENGINEER: 'Site Reliability Engineer',
  CLOUD_ARCHITECT: 'Cloud Architect',
  CLOUD_ENGINEER: 'Cloud Engineer',
  FIRMWARE_ENGINEER: 'Firmware Engineer',
  GAME_DEVELOPER: 'Game Developer',
  UNITY_DEVELOPER: 'Unity Developer',
  UNREAL_ENGINE_DEVELOPER: 'Unreal Engine Developer',
  QA_ENGINEER: 'QA Engineer',
  TEST_AUTOMATION_ENGINEER: 'Test Automation Engineer',
  BLOCKCHAIN_DEVELOPER: 'Blockchain Developer',
  AR_VR_DEVELOPER: 'AR/VR Developer',
  ROBOTICS_ENGINEER: 'Robotics Engineer',
  BLOCKCHAIN_ARCHITECT: 'Blockchain Architect',

  // Data Science
  DATA_SCIENTIST: 'Data Scientist',
  SENIOR_DATA_SCIENTIST: 'Senior Data Scientist',
  LEAD_DATA_SCIENTIST: 'Lead Data Scientist',
  DATA_ANALYST: 'Data Analyst',
  DATA_ENGINEER: 'Data Engineer',
  ETL_DEVELOPER: 'ETL Developer',
  MACHINE_LEARNING_ENGINEER: 'Machine Learning Engineer',
  AI_RESEARCHER: 'AI Researcher',
  NLP_ENGINEER: 'NLP Engineer',
  COMPUTER_VISION_ENGINEER: 'Computer Vision Engineer',

  // Business & Project Management
  BUSINESS_ANALYST: 'Business Analyst',
  PRODUCT_MANAGER: 'Product Manager',
  TECHNICAL_PRODUCT_MANAGER: 'Technical Product Manager',
  PROJECT_MANAGER: 'Project Manager',
  IT_PROJECT_MANAGER: 'IT Project Manager',
  SCRUM_MASTER: 'Scrum Master',
  PRODUCT_OWNER: 'Product Owner',
  BUSINESS_SYSTEMS_ANALYST: 'Business Systems Analyst',

  // Design
  UI_UX_DESIGNER: 'UI/UX Designer',
  UI_DESIGNER: 'UI Designer',
  UX_DESIGNER: 'UX Designer',
  PRODUCT_DESIGNER: 'Product Designer',
  GRAPHIC_DESIGNER: 'Graphic Designer',
  MOTION_DESIGNER: 'Motion Designer',
  WEB_DESIGNER: 'Web Designer',

  // IT & Systems Administration
  NETWORK_ENGINEER: 'Network Engineer',
  SYSTEMS_ADMINISTRATOR: 'Systems Administrator',
  DATABASE_ADMINISTRATOR: 'Database Administrator',
  IT_SUPPORT_SPECIALIST: 'IT Support Specialist',
  HELPDESK_TECHNICIAN: 'Helpdesk Technician',
  SYSTEM_ENGINEER: 'System Engineer',
  SECURITY_ENGINEER: 'Security Engineer',

  // IT Management
  IT_MANAGER: 'IT Manager',
  TECHNICAL_LEAD: 'Technical Lead',
  ENGINEERING_MANAGER: 'Engineering Manager',
  DEVELOPMENT_MANAGER: 'Development Manager',

  // Sales & Customer Support
  SALES_ENGINEER: 'Sales Engineer',
  SOLUTIONS_ARCHITECT: 'Solutions Architect',
  PRE_SALES_CONSULTANT: 'Pre-Sales Consultant',
  CUSTOMER_SUCCESS_MANAGER: 'Customer Success Manager',
  TECHNICAL_ACCOUNT_MANAGER: 'Technical Account Manager',

  // IT Consulting
  IT_CONSULTANT: 'IT Consultant',
  TECHNOLOGY_CONSULTANT: 'Technology Consultant',
  ERP_CONSULTANT: 'ERP Consultant',
  CRM_CONSULTANT: 'CRM Consultant',
};

export const industries = {
  // Accounting
  ACCOUNTS_OFFICERS_CLERKS: 'Accounts Officers/Clerks',
  ACCOUNTS_PAYABLE: 'Accounts Payable',
  ACCOUNTS_RECEIVABLE_CREDIT_CONTROL: 'Accounts Receivable/Credit Control',
  ANALYSIS_REPORTING: 'Analysis & Reporting',
  ASSISTANT_ACCOUNTANTS: 'Assistant Accountants',
  AUDIT_EXTERNAL: 'Audit - External',
  AUDIT_INTERNAL: 'Audit - Internal',
  BOOKKEEPING_SMALL_PRACTICE_ACCOUNTING: 'Bookkeeping & Small Practice Accounting',
  BUSINESS_SERVICES_CORPORATE_ADVISORY: 'Business Services & Corporate Advisory',
  COMPANY_SECRETARIES: 'Company Secretaries',
  COMPLIANCE_RISK: 'Compliance & Risk',
  COST_ACCOUNTING: 'Cost Accounting',
  FINANCIAL_ACCOUNTING_REPORTING: 'Financial Accounting & Reporting',
  FINANCIAL_MANAGERS_CONTROLLERS: 'Financial Managers & Controllers',
  FORENSIC_ACCOUNTING_INVESTIGATION: 'Forensic Accounting & Investigation',
  INSOLVENCY_CORPORATE_RECOVERY: 'Insolvency & Corporate Recovery',
  INVENTORY_FIXED_ASSETS: 'Inventory & Fixed Assets',
  MANAGEMENT: 'Management',
  MANAGEMENT_ACCOUNTING_BUDGETING: 'Management Accounting & Budgeting',
  PAYROLL: 'Payroll',
  STRATEGY_PLANNING: 'Strategy & Planning',
  SYSTEMS_ACCOUNTING_IT_AUDIT: 'Systems Accounting & IT Audit',
  TAXATION: 'Taxation',
  TREASURY: 'Treasury',

  // Administration & Office Support
  ADMINISTRATIVE_ASSISTANTS: 'Administrative Assistants',
  CLIENT_SALES_ADMINISTRATION: 'Client & Sales Administration',
  CONTRACTS_ADMINISTRATION: 'Contracts Administration',
  DATA_ENTRY_WORD_PROCESSING: 'Data Entry & Word Processing',
  OFFICE_MANAGEMENT: 'Office Management',
  PA_EA_SECRETARIAL: 'PA, EA & Secretarial',
  RECEPTIONISTS: 'Receptionists',
  RECORDS_MANAGEMENT_DOCUMENT_CONTROL: 'Records Management & Document Control',

  // Advertising, Arts & Media
  AGENCY_ACCOUNT_MANAGEMENT: 'Agency Account Management',
  ART_DIRECTION: 'Art Direction',
  EDITING_PUBLISHING: 'Editing & Publishing',
  EVENT_MANAGEMENT: 'Event Management',
  JOURNALISM_WRITING: 'Journalism & Writing',
  MEDIA_STRATEGY_PLANNING_BUYING: 'Media Strategy, Planning & Buying',
  PERFORMING_ARTS: 'Performing Arts',
  PHOTOGRAPHY: 'Photography',
  PROGRAMMING_PRODUCTION: 'Programming & Production',
  PROMOTIONS: 'Promotions',
  BANKING_FINANCIAL_SERVICES: 'Banking & Financial Services',

  // Call Centre & Customer Service
  COLLECTIONS: 'Collections',
  CUSTOMER_SERVICE_CALL_CENTRE: 'Customer Service - Call Centre',
  CUSTOMER_SERVICE_CUSTOMER_FACING: 'Customer Service - Customer Facing',
  MANAGEMENT_SUPPORT: 'Management & Support',
  SALES_INBOUND: 'Sales - Inbound',
  SALES_OUTBOUND: 'Sales - Outbound',
  SUPERVISORS_TEAM_LEADERS: 'Supervisors/Team Leaders',

  // CEO & General Management
  BOARD_APPOINTMENTS: 'Board Appointments',
  CEO: 'CEO',
  COO_MD: 'COO & MD',
  GENERAL_BUSINESS_UNIT_MANAGER: 'General/Business Unit Manager',

  // Community Services & Development'
  AGED_DISABILITY_SUPPORT: 'Aged & Disability Support',
  CHILD_WELFARE_YOUTH_FAMILY_SERVICES: 'Child Welfare, Youth & Family Services',
  COMMUNITY_DEVELOPMENT: 'Community Development',
  EMPLOYMENT_SERVICES: 'Employment Services',
  FUNDRAISING: 'Fundraising',
  HOUSING_HOMELESSNESS_SERVICES: 'Housing & Homelessness Services',
  INDIGENOUS_MULTICULTURAL_SERVICES: 'Indigenous & Multicultural Services',
  VOLUNTEER_COORDINATION_SUPPORT: 'Volunteer Coordination & Support',

  // Construction
  CONTRACTS_MANAGEMENT: 'Contracts Management',
  ESTIMATING: 'Estimating',
  FOREPERSON_SUPERVISORS: 'Foreperson/Supervisors',
  HEALTH_SAFETY_ENVIRONMENT: 'Health, Safety & Environment',
  PLANNING_SCHEDULING: 'Planning & Scheduling',
  PLANT_MACHINERY_OPERATORS: 'Plant & Machinery Operators',
  PROJECT_MANAGEMENT: 'Project Management',
  QUALITY_ASSURANCE_CONTROL: 'Quality Assurance & Control',
  SURVEYING: 'Surveying',
  CONSULTING_STRATEGY: 'Consulting & Strategy',

  // Design & Architecture
  ARCHITECTURAL_DRAFTING: 'Architectural Drafting',
  ARCHITECTURE: 'Architecture',
  FASHION_TEXTILE_DESIGN: 'Fashion & Textile Design',
  GRAPHIC_DESIGN: 'Graphic Design',
  ILLUSTRATION_ANIMATION: 'Illustration & Animation',
  INDUSTRIAL_DESIGN: 'Industrial Design',
  INTERIOR_DESIGN: 'Interior Design',
  LANDSCAPE_ARCHITECTURE: 'Landscape Architecture',
  URBAN_DESIGN_PLANNING: 'Urban Design & Planning',
  WEB_INTERACTION_DESIGN: 'Web & Interaction Design',

  // Education & Training
  CHILDCARE_OUTSIDE_SCHOOL_HOURS_CARE: 'Childcare & Outside School Hours Care',
  LIBRARY_SERVICES_INFORMATION_MANAGEMENT: 'Library Services & Information Management',
  MANAGEMENT_SCHOOLS: 'Management - Schools',
  MANAGEMENT_UNIVERSITIES: 'Management - Universities',
  MANAGEMENT_VOCATIONAL: 'Management - Vocational',
  RESEARCH_FELLOWSHIPS: 'Research & Fellowships',
  STUDENT_SERVICES: 'Student Services',
  TEACHING_EARLY_CHILDHOOD: 'Teaching - Early Childhood',
  TEACHING_PRIMARY: 'Teaching - Primary',
  TEACHING_SECONDARY: 'Teaching - Secondary',
  TEACHING_TERTIARY: 'Teaching - Tertiary',
  TEACHING_VOCATIONAL: 'Teaching - Vocational',
  TEACHING_AIDES_SPECIAL_NEEDS: 'Teaching Aides & Special Needs',
  TUTORING: 'Tutoring',
  WORKPLACE_TRAINING_ASSESSMENT: 'Workplace Training & Assessment',

  // Engineering
  AEROSPACE_ENGINEERING: 'Aerospace Engineering',
  AUTOMOTIVE_ENGINEERING: 'Automotive Engineering',
  BUILDING_SERVICES_ENGINEERING: 'Building Services Engineering',
  CHEMICAL_ENGINEERING: 'Chemical Engineering',
  CIVIL_STRUCTURAL_ENGINEERING: 'Civil/Structural Engineering',
  ELECTRICAL_ELECTRONIC_ENGINEERING: 'Electrical/Electronic Engineering',
  ENGINEERING_DRAFTING: 'Engineering Drafting',
  ENVIRONMENTAL_ENGINEERING: 'Environmental Engineering',
  FIELD_ENGINEERING: 'Field Engineering',
  INDUSTRIAL_ENGINEERING: 'Industrial Engineering',
  MAINTENANCE: 'Maintenance',
  MATERIALS_HANDLING_ENGINEERING: 'Materials Handling Engineering',
  MECHANICAL_ENGINEERING: 'Mechanical Engineering',
  PROCESS_ENGINEERING: 'Process Engineering',
  PROJECT_ENGINEERING: 'Project Engineering',
  SUPERVISORS: 'Supervisors',
  SYSTEMS_ENGINEERING: 'Systems Engineering',
  WATER_WASTE_ENGINEERING: 'Water & Waste Engineering',

  // Farming, Animals & Conservation
  AGRONOMY_FARM_SERVICES: 'Agronomy & Farm Services',
  CONSERVATION_PARKS_WILDLIFE: 'Conservation, Parks & Wildlife',
  FARM_LABOUR: 'Farm Labour',
  FARM_MANAGEMENT: 'Farm Management',
  FISHING_AQUACULTURE: 'Fishing & Aquaculture',
  HORTICULTURE: 'Horticulture',
  VETERINARY_SERVICES_ANIMAL_WELFARE: 'Veterinary Services & Animal Welfare',
  WINERY_VITICULTURE: 'Winery & Viticulture',

  // Government & Defence
  AIR_FORCE: 'Air Force',
  ARMY: 'Army',
  EMERGENCY_SERVICES: 'Emergency Services',
  GOVERNMENT_FEDERAL: 'Government - Federal',
  GOVERNMENT_LOCAL: 'Government - Local',
  GOVERNMENT_STATE: 'Government - State',
  NAVY: 'Navy',
  POLICE_CORRECTIONS: 'Police & Corrections',
  POLICY_PLANNING_REGULATION: 'Policy, Planning & Regulation',

  // Healthcare & Medical
  AMBULANCE_PARAMEDICS: 'Ambulance/Paramedics',
  CHIROPRACTIC_OSTEOPATHIC: 'Chiropractic & Osteopathic',
  CLINICAL_MEDICAL_RESEARCH: 'Clinical/Medical Research',
  DENTAL: 'Dental',
  DIETICIANS: 'Dieticians',
  ENVIRONMENTAL_SERVICES: 'Environmental Services',
  GENERAL_PRACTITIONERS: 'General Practitioners',
  MEDICAL_ADMINISTRATION: 'Medical Administration',
  MEDICAL_IMAGING: 'Medical Imaging',
  MEDICAL_SPECIALISTS: 'Medical Specialists',
  NATURAL_THERAPIES_ALTERNATIVE_MEDICINE: 'Natural Therapies & Alternative Medicine',
  NURSING_AE_CRITICAL_CARE_ICU: 'Nursing - A&E, Critical Care & ICU',
  NURSING_AGED_CARE: 'Nursing - Aged Care',
  NURSING_COMMUNITY_MATERNAL_CHILD_HEALTH: 'Nursing - Community, Maternal & Child Health',
  NURSING_EDUCATORS_FACILITATORS: 'Nursing - Educators & Facilitators',
  NURSING_GENERAL_MEDICAL_SURGICAL: 'Nursing - General Medical & Surgical',
  NURSING_HIGH_ACUITY: 'Nursing - High Acuity',
  NURSING_MANAGEMENT: 'Nursing - Management',
  NURSING_MIDWIFERY_NEO_NATAL_SCN_NICU: 'Nursing - Midwifery, Neo-Natal, SCN & NICU',
  NURSING_PAEDIATRIC_PICU: 'Nursing - Paediatric & PICU',
  NURSING_PSYCH_FORNSIC_CORRECTIONAL_HEALTH: 'Nursing - Psych, Forensic & Correctional Health',
  NURSING_THEATRE_RECOVERY: 'Nursing - Theatre & Recovery',
  OPTICAL: 'Optical',
  PATHOLOGY: 'Pathology',
  PHARMACEUTICALS_MEDICAL_DEVICES: 'Pharmaceuticals & Medical Devices',
  PHARMACY: 'Pharmacy',
  PHYSIOTHERAPY_OT_REHABILITATION: 'Physiotherapy, OT & Rehabilitation',
  PSYCHOLOGY_COUNSELLING_SOCIAL_WORK: 'Psychology, Counselling & Social Work',
  RESIDENTS_REGISTRARS: 'Residents & Registrars',

  // Hospitality & Tourism
  AIRLINES: 'Airlines',
  BAR_BEVERAGE_STAFF: 'Bar & Beverage Staff',
  CHEFS_COOKS: 'Chefs/Cooks',
  FRONT_OFFICE_GUEST_SERVICES: 'Front Office & Guest Services',
  GAMING: 'Gaming',
  HOUSEKEEPING: 'Housekeeping',
  KITCHEN_SANDWICH_HANDS: 'Kitchen & Sandwich Hands',
  RESERVATIONS: 'Reservations',
  TOUR_GUIDES: 'Tour Guides',
  TRAVEL_AGENTS_CONSULTANTS: 'Travel Agents/Consultants',
  WAITING_STAFF: 'Waiting Staff',

  // Human Resources & Recruitment
  HUMAN_RESOURCE_DEVELOPMENT: 'Human Resource & Development',
  CONSULTING_GENERALIST_HR: 'Consulting & Generalist HR',
  INDUSTRIAL_EMPLOYEE_RELATIONS: 'Industrial & Employee Relations',
  MANAGEMENT_AGENCY: 'Management - Agency',
  MANAGEMENT_INTERNAL: 'Management - Internal',
  OCCUPATIONAL_HEALTH_SAFETY: 'Occupational Health & Safety',
  ORGANISATIONAL_DEVELOPMENT: 'Organisational Development',
  RECRUITMENT_AGENCY: 'Recruitment - Agency',
  RECRUITMENT_INTERNAL: 'Recruitment - Internal',
  REMUNERATION_BENEFITS: 'Remuneration & Benefits',
  TRAINING_DEVELOPMENT: 'Training & Development',

  // Information & Communication Technology
  INFORMATION_TECHNOLOGY: 'Information & Technology',
  ARCHITECTS: 'Architects',
  BUSINESS_SYSTEMS_ANALYSTS: 'Business/Systems Analysts',
  COMPUTER_OPERATORS: 'Computer Operators',
  CONSULTANTS: 'Consultants',
  DATABASE_DEVELOPMENT_ADMINISTRATION: 'Database Development & Administration',
  DEVELOPERS_PROGRAMMERS: 'Developers/Programmers',
  ENGINEERING_HARDWARE: 'Engineering - Hardware',
  ENGINEERING_NETWORK: 'Engineering - Network',
  ENGINEERING_SOFTWARE: 'Engineering - Software',
  HELP_DESK_IT_SUPPORT: 'Help Desk & IT Support',
  NETWORKS_SYSTEMS_ADMINISTRATION: 'Networks & Systems Administration',
  PRODUCT_MANAGEMENT_DEVELOPMENT: 'Product Management & Development',
  PROGRAMME_PROJECT_MANAGEMENT: 'Programme & Project Management',
  SALES_PRE_POST: 'Sales - Pre & Post',
  SECURITY: 'Security',
  TEAM_LEADERS: 'Team Leaders',
  TECHNICAL_WRITING: 'Technical Writing',
  TELECOMMUNICATIONS: 'Telecommunications',
  TESTING_QUALITY_ASSURANCE: 'Testing & Quality Assurance',
  WEB_DEVELOPMENT_PRODUCTION: 'Web Development & Production',

  // Insurance & Superannuation
  ACTUARIAL: 'Actuarial',
  ASSESSMENT: 'Assessment',
  BROKERAGE: 'Brokerage',
  CLAIMS: 'Claims',
  FUND_ADMINISTRATION: 'Fund Administration',
  RISK_CONSULTING: 'Risk Consulting',
  SUPERANNUATION: 'Superannuation',
  UNDERWRITING: 'Underwriting',
  WORKERS_COMPENSATION: "Workers' Compensation",

  // Legal
  BANKING_FINANCE_LAW: 'Banking & Finance Law',
  CONSTRUCTION_LAW: 'Construction Law',
  CORPORATE_COMMERCIAL_LAW: 'Corporate & Commercial Law',
  CRIMINAL_CIVIL_LAW: 'Criminal & Civil Law',
  ENVIRONMENT_PLANNING_LAW: 'Environment & Planning Law',
  FAMILY_LAW: 'Family Law',
  GENERALISTS_IN_HOUSE: 'Generalists - In-house',
  GENERALISTS_LAW_FIRM: 'Generalists - Law Firm',
  INDUSTRIAL_RELATIONS_EMPLOYMENT_LAW: 'Industrial Relations & Employment Law',
  INSURANCE_SUPERANNUATION_LAW: 'Insurance & Superannuation Law',
  INTELLECTUAL_PROPERTY_LAW: 'Intellectual Property Law',
  LAW_CLERKS_PARAPLEGALS: 'Law Clerks & Paralegals',
  LEGAL_PRACTICE_MANAGEMENT: 'Legal Practice Management',
  LEGAL_SECRETARIES: 'Legal Secretaries',
  LITIGATION_DISPUTE_RESOLUTION: 'Litigation & Dispute Resolution',
  PERSONAL_INJURY_LAW: 'Personal Injury Law',
  PROPERTY_LAW: 'Property Law',
  TAX_LAW: 'Tax Law',

  // Manufacturing, Transport & Logistics
  ASSEMBLY_PROCESS_WORK: 'Assembly & Process Work',
  AVIATION_SERVICES: 'Aviation Services',
  COURIERS_DRIVERS_POSTAL_SERVICES: 'Couriers, Drivers & Postal Services',
  FLEET_MANAGEMENT: 'Fleet Management',
  FREIGHT_CARGO_FORWARDING: 'Freight/Cargo Forwarding',
  IMPORT_EXPORT_CUSTOMS: 'Import/Export & Customs',
  MACHINE_OPERATORS: 'Machine Operators',
  PATTERN_MAKERS_GARMENT_TECHNICIANS: 'Pattern Makers & Garment Technicians',
  PICKERS_PACKERS: 'Pickers & Packers',
  PRODUCTION_PLANNING_SCHEDULING: 'Production, Planning & Scheduling',
  PUBLIC_TRANSPORT_TAXI_SERVICES: 'Public Transport & Taxi Services',
  PURCHASING_PROCUREMENT_INVENTORY: 'Purchasing, Procurement & Inventory',
  RAIL_MARITIME_TRANSPORT: 'Rail & Maritime Transport',
  ROAD_TRANSPORT: 'Road Transport',
  TEAM_LEADERS_SUPERVISORS: 'Team Leaders/Supervisors',
  WAREHOUSING_STORAGE_DISTRIBUTION: 'Warehousing, Storage & Distribution',

  // Marketing & Communications
  BRAND_MANAGEMENT: 'Brand Management',
  DIGITAL_SEARCH_MARKETING: 'Digital & Search Marketing',
  DIRECT_MARKETING_CRM: 'Direct Marketing & CRM',
  INTERNAL_COMMUNICATIONS: 'Internal Communications',
  MARKET_RESEARCH_ANALYSIS: 'Market Research & Analysis',
  MARKETING_ASSISTANTS_COORDINATORS: 'Marketing Assistants/Coordinators',
  MARKETING_COMMUNICATIONS: 'Marketing Communications',
  PUBLIC_RELATIONS_CORPORATE_AFFAIRS: 'Public Relations & Corporate Affairs',
  TRADE_MARKETING: 'Trade Marketing',

  // Mining, Resources & Energy
  MINING_DRILL_BLAST: 'Mining - Drill & Blast',
  MINING_ENGINEERING_MAINTENANCE: 'Mining - Engineering & Maintenance',
  MINING_EXPLORATION_GEOSCIENCE: 'Mining - Exploration & Geoscience',
  MINING_OPERATIONS: 'Mining - Operations',
  MINING_PROCESSING: 'Mining - Processing',
  NATURAL_RESOURCES_WATER: 'Natural Resources & Water',
  OIL_GAS_DRILLING: 'Oil & Gas - Drilling',
  OIL_GAS_ENGINEERING_MAINTENANCE: 'Oil & Gas - Engineering & Maintenance',
  OIL_GAS_EXPLORATION_GEOSCIENCE: 'Oil & Gas - Exploration & Geoscience',
  OIL_GAS_OPERATIONS: 'Oil & Gas - Operations',
  OIL_GAS_PRODUCTION_REFINEMENT: 'Oil & Gas - Production & Refinement',
  POWER_GENERATION_DISTRIBUTION: 'Power Generation & Distribution',

  // Real Estate & Property
  ADMINISTRATION: 'Administration',
  ANALYSTS: 'Analysts',
  BODY_CORPORATE_FACILITIES_MANAGEMENT: 'Body Corporate & Facilities Management',
  COMMERCIAL_SALES_LEASING_PROPERTY_MGMT: 'Commercial Sales, Leasing & Property Mgmt',
  RESIDENTIAL_LEASING_PROPERTY_MANAGEMENT: 'Residential Leasing & Property Management',
  RESIDENTIAL_SALES: 'Residential Sales',
  RETAIL_PROPERTY_DEVELOPMENT: 'Retail & Property Development',
  VALUATION: 'Valuation',

  // Retail & Consumer Products
  BUYING: 'Buying',
  MANAGEMENT_AREA_MULTI_SITE: 'Management - Area/Multi-site',
  MANAGEMENT_DEPARTMENT_ASSISTANT: 'Management - Department/Assistant',
  MANAGEMENT_STORE: 'Management - Store',
  MERCHANDISERS: 'Merchandisers',
  PLANNING: 'Planning',
  RETAIL_ASSISTANTS: 'Retail Assistants',

  // Sales
  SPEECH_THERAPY: 'Speech Therapy',
  ACCOUNT_RELATIONSHIP_MANAGEMENT: 'Account & Relationship Management',
  NEW_BUSINESS_DEVELOPMENT: 'New Business Development',
  SALES_COORDINATORS: 'Sales Coordinators',
  SALES_REPRESENTATIVES_CONSULTANTS: 'Sales Representatives/Consultants',

  // Science & Technology
  BIOLOGICAL_BIOMEDICAL_SCIENCES: 'Biological & Biomedical Sciences',
  BIOTECHNOLOGY_GENETICS: 'Biotechnology & Genetics',
  CHEMISTRY_PHYSICS: 'Chemistry & Physics',
  ENVIRONMENTAL_EARTH_GEOSCIENCES: 'Environmental, Earth & Geosciences',
  FOOD_TECHNOLOGY_SAFETY: 'Food Technology & Safety',
  LABORATORY_TECHNICAL_SERVICES: 'Laboratory & Technical Services',
  MATERIALS_SCIENCES: 'Materials Sciences',
  MATHEMATICS_STATISTICS_INFORMATION_SCIENCES: 'Mathematics, Statistics & Information Sciences',
  MODELLING_SIMULATION: 'Modelling & Simulation',

  // Self Employment
  SELF_EMPLOYMENT: 'Self Employment',

  // Sport & Recreation
  COACHING_INSTRUCTION: 'Coaching & Instruction',
  FITNESS_PERSONAL_TRAINING: 'Fitness & Personal Training',

  // Trades & Services
  AIR_CONDITIONING_REFRIGERATION: 'Air Conditioning & Refrigeration',
  AUTOMOTIVE_TRADES: 'Automotive Trades',
  BAKERS_PASTRY_CHEFS: 'Bakers & Pastry Chefs',
  BUILDING_TRADES: 'Building Trades',
  BUTCHERS: 'Butchers',
  CARPENTRY_CABINET_MAKING: 'Carpentry & Cabinet Making',
  CLEANING_SERVICES: 'Cleaning Services',
  ELECTRICIANS: 'Electricians',
  FITTERS_TURNERS_MACHINISTS: 'Fitters, Turners & Machinists',
  FLORISTRY: 'Floristry',
  GARDENING_LANDSCAPING: 'Gardening & Landscaping',
  HAIR_BEAUTY_SERVICES: 'Hair & Beauty Services',
  LABOURERS: 'Labourers',
  LOCKSMITHS: 'Locksmiths',
  MAINTENANCE_HANDYPERSON_SERVICES: 'Maintenance & Handyperson Services',
  NANNIES_BABYSITTERS: 'Nannies & Babysitters',
  PAINTERS_SIGN_WRITERS: 'Painters & Sign Writers',
  PLUMBERS: 'Plumbers',
  PRINTING_PUBLISHING_SERVICES: 'Printing & Publishing Services',
  SECURITY_SERVICES: 'Security Services',
  TAILORS_DRESSMAKERS: 'Tailors & Dressmakers',
  TECHNICIANS: 'Technicians',
  WELDERS_BOILERMAKERS: 'Welders & Boilermakers',
};

export const industriesWithCategory = {
  Accounting: [
    'Accounts Officers/Clerks',
    'Accounts Payable',
    'Accounts Receivable/Credit Control',
    'Analysis & Reporting',
    'Assistant Accountants',
    'Audit - External',
    'Audit - Internal',
    'Bookkeeping & Small Practice Accounting',
    'Business Services & Corporate Advisory',
    'Company Secretaries',
    'Compliance & Risk',
    'Cost Accounting',
    'Financial Accounting & Reporting',
    'Financial Managers & Controllers',
    'Forensic Accounting & Investigation',
    'Insolvency & Corporate Recovery',
    'Inventory & Fixed Assets',
    'Management',
    'Management Accounting & Budgeting',
    'Payroll',
    'Strategy & Planning',
    'Systems Accounting & IT Audit',
    'Taxation',
    'Treasury',
  ],
  'Administration & Office Support': [
    'Administrative Assistants',
    'Client & Sales Administration',
    'Contracts Administration',
    'Data Entry & Word Processing',
    'Office Management',
    'PA, EA & Secretarial',
    'Receptionists',
    'Records Management & Document Control',
  ],
  'Advertising, Arts & Media': [
    'Agency Account Management',
    'Art Direction',
    'Editing & Publishing',
    'Event Management',
    'Journalism & Writing',
    'Management',
    'Media Strategy, Planning & Buying',
    'Performing Arts',
    'Photography',
    'Programming & Production',
    'Promotions',
    'Banking & Financial Services',
  ],
  'Call Centre & Customer Service': [
    'Collections',
    'Customer Service - Call Centre',
    'Customer Service - Customer Facing',
    'Management & Support',
    'Sales - Inbound',
    'Sales - Outbound',
    'Supervisors/Team Leaders',
  ],
  'CEO & General Management': ['Board Appointments', 'CEO', 'COO & MD', 'General/Business Unit Manager'],
  'Community Services & Development': [
    'Aged & Disability Support',
    'Child Welfare, Youth & Family Services',
    'Community Development',
    'Employment Services',
    'Fundraising',
    'Housing & Homelessness Services',
    'Indigenous & Multicultural Services',
    'Management',
    'Volunteer Coordination & Support',
  ],
  Construction: [
    'Contracts Management',
    'Estimating',
    'Foreperson/Supervisors',
    'Health, Safety & Environment',
    'Planning & Scheduling',
    'Plant & Machinery Operators',
    'Project Management',
    'Quality Assurance & Control',
    'Surveying',
    'Consulting & Strategy',
  ],
  'Design & Architecture': [
    'Architectural Drafting',
    'Architecture',
    'Fashion & Textile Design',
    'Graphic Design',
    'Illustration & Animation',
    'Industrial Design',
    'Interior Design',
    'Landscape Architecture',
    'Urban Design & Planning',
    'Web & Interaction Design',
  ],
  'Education & Training': [
    'Childcare & Outside School Hours Care',
    'Library Services & Information Management',
    'Management - Schools',
    'Management - Universities',
    'Management - Vocational',
    'Research & Fellowships',
    'Student Services',
    'Teaching - Early Childhood',
    'Teaching - Primary',
    'Teaching - Secondary',
    'Teaching - Tertiary',
    'Teaching - Vocational',
    'Teaching Aides & Special Needs',
    'Tutoring',
    'Workplace Training & Assessment',
  ],
  Engineering: [
    'Aerospace Engineering',
    'Automotive Engineering',
    'Building Services Engineering',
    'Chemical Engineering',
    'Civil/Structural Engineering',
    'Electrical/Electronic Engineering',
    'Engineering Drafting',
    'Environmental Engineering',
    'Field Engineering',
    'Industrial Engineering',
    'Maintenance',
    'Management',
    'Materials Handling Engineering',
    'Mechanical Engineering',
    'Process Engineering',
    'Project Engineering',
    'Project Management',
    'Supervisors',
    'Systems Engineering',
    'Water & Waste Engineering',
  ],
  'Farming, Animals & Conservation': [
    'Agronomy & Farm Services',
    'Conservation, Parks & Wildlife',
    'Farm Labour',
    'Farm Management',
    'Fishing & Aquaculture',
    'Horticulture',
    'Veterinary Services & Animal Welfare',
    'Winery & Viticulture',
  ],
  'Government & Defence': [
    'Air Force',
    'Army',
    'Emergency Services',
    'Government - Federal',
    'Government - Local',
    'Government - State',
    'Navy',
    'Police & Corrections',
    'Policy, Planning & Regulation',
  ],
  'Healthcare & Medical': [
    'Ambulance/Paramedics',
    'Chiropractic & Osteopathic',
    'Clinical/Medical Research',
    'Dental',
    'Dieticians',
    'Environmental Services',
    'General Practitioners',
    'Medical Administration',
    'Medical Imaging',
    'Medical Specialists',
    'Natural Therapies & Alternative Medicine',
    'Nursing - A&E, Critical Care & ICU',
    'Nursing - Aged Care',
    'Nursing - Community, Maternal & Child Health',
    'Nursing - Educators & Facilitators',
    'Nursing - General Medical & Surgical',
    'Nursing - High Acuity',
    'Nursing - Management',
    'Nursing - Midwifery, Neo-Natal, SCN & NICU',
    'Nursing - Paediatric & PICU',
    'Nursing - Psych, Forensic & Correctional Health',
    'Nursing - Theatre & Recovery',
    'Optical',
    'Pathology',
    'Pharmaceuticals & Medical Devices',
    'Pharmacy',
    'Physiotherapy, OT & Rehabilitation',
    'Psychology, Counselling & Social Work',
    'Residents & Registrars',
  ],
  'Hospitality & Tourism': [
    'Airlines',
    'Bar & Beverage Staff',
    'Chefs/Cooks',
    'Front Office & Guest Services',
    'Gaming',
    'Housekeeping',
    'Kitchen & Sandwich Hands',
    'Management',
    'Reservations',
    'Tour Guides',
    'Travel Agents/Consultants',
    'Waiting Staff',
  ],
  'Human Resources & Recruitment': [
    'Human Resource & Development',
    'Consulting & Generalist HR',
    'Industrial & Employee Relations',
    'Management - Agency',
    'Management - Internal',
    'Occupational Health & Safety',
    'Organisational Development',
    'Recruitment - Agency',
    'Recruitment - Internal',
    'Remuneration & Benefits',
    'Training & Development',
  ],
  'Information & Communication Technology': [
    'Information & Technology',
    'Architects',
    'Business/Systems Analysts',
    'Computer Operators',
    'Consultants',
    'Database Development & Administration',
    'Developers/Programmers',
    'Engineering - Hardware',
    'Engineering - Network',
    'Engineering - Software',
    'Help Desk & IT Support',
    'Networks & Systems Administration',
    'Product Management & Development',
    'Programme & Project Management',
    'Sales - Pre & Post',
    'Security',
    'Team Leaders',
    'Technical Writing',
    'Telecommunications',
    'Testing & Quality Assurance',
    'Web Development & Production',
  ],
  'Insurance & Superannuation': [
    'Actuarial',
    'Assessment',
    'Brokerage',
    'Claims',
    'Fund Administration',
    'Risk Consulting',
    'Superannuation',
    'Underwriting',
    "Workers' Compensation",
  ],
  Legal: [
    'Banking & Finance Law',
    'Construction Law',
    'Corporate & Commercial Law',
    'Criminal & Civil Law',
    'Environment & Planning Law',
    'Family Law',
    'Generalists - In-house',
    'Generalists - Law Firm',
    'Industrial Relations & Employment Law',
    'Insurance & Superannuation Law',
    'Intellectual Property Law',
    'Law Clerks & Paralegals',
    'Legal Practice Management',
    'Legal Secretaries',
    'Litigation & Dispute Resolution',
    'Personal Injury Law',
    'Property Law',
    'Tax Law',
  ],
  'Manufacturing, Transport & Logistics': [
    'Analysis & Reporting',
    'Assembly & Process Work',
    'Aviation Services',
    'Couriers, Drivers & Postal Services',
    'Fleet Management',
    'Freight/Cargo Forwarding',
    'Import/Export & Customs',
    'Machine Operators',
    'Management',
    'Pattern Makers & Garment Technicians',
    'Pickers & Packers',
    'Production, Planning & Scheduling',
    'Public Transport & Taxi Services',
    'Purchasing, Procurement & Inventory',
    'Quality Assurance & Control',
    'Rail & Maritime Transport',
    'Road Transport',
    'Team Leaders/Supervisors',
    'Warehousing, Storage & Distribution',
  ],
  'Marketing & Communications': [
    'Brand Management',
    'Digital & Search Marketing',
    'Direct Marketing & CRM',
    'Event Management',
    'Internal Communications',
    'Management',
    'Market Research & Analysis',
    'Marketing Assistants/Coordinators',
    'Marketing Communications',
    'Product Management & Development',
    'Public Relations & Corporate Affairs',
    'Trade Marketing',
  ],
  'Mining, Resources & Energy': [
    'Analysis & Reporting',
    'Health, Safety & Environment',
    'Management',
    'Mining - Drill & Blast',
    'Mining - Engineering & Maintenance',
    'Mining - Exploration & Geoscience',
    'Mining - Operations',
    'Mining - Processing',
    'Natural Resources & Water',
    'Oil & Gas - Drilling',
    'Oil & Gas - Engineering & Maintenance',
    'Oil & Gas - Exploration & Geoscience',
    'Oil & Gas - Operations',
    'Oil & Gas - Production & Refinement',
    'Power Generation & Distribution',
    'Surveying',
  ],
  'Real Estate & Property': [
    'Administration',
    'Analysts',
    'Body Corporate & Facilities Management',
    'Commercial Sales, Leasing & Property Mgmt',
    'Residential Leasing & Property Management',
    'Residential Sales',
    'Retail & Property Development',
    'Valuation',
  ],
  'Retail & Consumer Products': [
    'Buying',
    'Management - Area/Multi-site',
    'Management - Department/Assistant',
    'Management - Store',
    'Merchandisers',
    'Planning',
    'Retail Assistants',
  ],
  Sales: [
    'Speech Therapy',
    'Account & Relationship Management',
    'Analysis & Reporting',
    'Management',
    'New Business Development',
    'Sales Coordinators',
    'Sales Representatives/Consultants',
  ],
  'Science & Technology': [
    'Biological & Biomedical Sciences',
    'Biotechnology & Genetics',
    'Chemistry & Physics',
    'Environmental, Earth & Geosciences',
    'Food Technology & Safety',
    'Laboratory & Technical Services',
    'Materials Sciences',
    'Mathematics, Statistics & Information Sciences',
    'Modelling & Simulation',
    'Quality Assurance & Control',
  ],
  'Self Employment': [],
  'Sport & Recreation': ['Coaching & Instruction', 'Fitness & Personal Training', 'Management'],
  'Trades & Services': [
    'Air Conditioning & Refrigeration',
    'Automotive Trades',
    'Bakers & Pastry Chefs',
    'Building Trades',
    'Butchers',
    'Carpentry & Cabinet Making',
    'Cleaning Services',
    'Electricians',
    'Fitters, Turners & Machinists',
    'Floristry',
    'Gardening & Landscaping',
    'Hair & Beauty Services',
    'Labourers',
    'Locksmiths',
    'Maintenance & Handyperson Services',
    'Nannies & Babysitters',
    'Painters & Sign Writers',
    'Plumbers',
    'Printing & Publishing Services',
    'Security Services',
    'Tailors & Dressmakers',
    'Technicians',
    'Welders & Boilermakers',
  ],
};

export const currencyTypes = {
  MYR: 'MYR',
};

export const notificationTypes = {
  JOB_RECOMMENDATION: 'Job Recommendation',
  CANDIDATE_APPLY: 'Candidate Apply',
  JOB_STATUS_UPDATED: 'Job Status Updated',
  JOB_APPLICATION_STATUS_UPDATED: 'Job Application Status Updated',
  JOB_ADS_EXPIRED: 'Job Ads Expired',
  OTHER: 'Other',
};

export const transactionStatusTypes = {
  PENDING: 'Pending',
  SUCCESS: 'Success',
  FAILED: 'Failed',
  EXPIRED: 'Expired',
};

// Define the url as constants for reuse in src/middleware/conditionalBodyParser.ts
export const mainUrlForStripeWebhookEvent = 'transactions';
export const subUrlForStripeWebhookEvent = 'webhook/stripe';

export const languagesTypes = {
  AFRIKAANS: 'Afrikaans',
  ARABIC: 'Arabic',
  BENGALI: 'Bengali',
  BULGARIAN: 'Bulgarian',
  BURMESE: 'Burmese',
  CANTONESE: 'Cantonese',
  CHINESE: 'Chinese',
  CROATIAN: 'Croatian',
  CZECH: 'Czech',
  DANISH: 'Danish',
  DUTCH: 'Dutch',
  ENGLISH: 'English',
  ESTONIAN: 'Estonian',
  FILIPINO: 'Filipino',
  FINNISH: 'Finnish',
  FRENCH: 'French',
  FRENCH_CIRIL: 'French Ciril',
  GERMAN: 'German',
  GREEK: 'Greek',
  HEBREW: 'Hebrew',
  HINDI: 'Hindi',
  HUNGARIAN: 'Hungarian',
  INDONESIAN: 'Indonesian',
  IRISH: 'Irish',
  ITALIAN: 'Italian',
  ITALIAN_CIRIL: 'Italian Ciril',
  JAPANESE: 'Japanese',
  JAPANESE_CIRIL: 'Japanese Ciril',
  KOREAN: 'Korean',
  KOREAN_CIRIL: 'Korean Ciril',
  LAO: 'Lao',
  LATIN: 'Latin',
  LATVIAN: 'Latvian',
  LITHUANIAN: 'Lithuanian',
  MALAY: 'Malay',
  MANDARIN: 'Mandarin',
  MARATHI: 'Marathi',
  NORWEGIAN: 'Norwegian',
  PERSIAN: 'Persian',
  POLISH: 'Polish',
  PORTUGUESE: 'Portuguese',
  PUNJABI: 'Punjabi',
  ROMANIAN: 'Romanian',
  RUSSIAN: 'Russian',
  SPANISH: 'Spanish',
  SWAHILI: 'Swahili',
  SWEDISH: 'Swedish',
  TAMIL: 'Tamil',
  TELUGU: 'Telugu',
  THAI: 'Thai',
  TURKISH: 'Turkish',
  TURKISH_CIRIL: 'Turkish Ciril',
  UKRAINIAN: 'Ukrainian',
  URDU: 'Urdu',
  VIETNAMESE: 'Vietnamese',
  VIETNAMESE_CIRIL: 'Vietnamese Ciril',
};

export const packageModelTypes = {
  PACKAGE: 'Package',
  TALENT_SEARCH_PACKAGE: 'TalentSearchPackage',
};

export const whereDidYourHear = {
  GOOGLE: 'Google',
  LINKEDIN: 'LinkedIn',
  EVENT: 'Event',
  FRIENDS: 'Friends',
  COLLEAGUE: 'Colleague',
  SOCIAL_MEDIA: 'Social Media',
  OTHER: 'Other',
};

export const languageProficiencyTypes = {
  ELEMENTARY_PROFICIENCY: 'Elementary proficiency',
  LIMITED_WORKING_PROFICIENCY: 'Limited working proficiency',
  PROFESSIONAL_WORKING_PROFICIENCY: 'Professional working proficiency',
  FULL_PROFESSIONAL_PROFICIENCY: 'Full professional proficiency',
  NATIVE_OR_BILINGUAL_PROFICIENCY: 'Native or bilingual proficiency',
};

export const JOB_POSTED_SORTED = [
  { key: 'Date posted', value: { createdAt: -1 } },
  { key: 'Date modified', value: { updatedAt: -1 } },
  { key: 'Alphabetical', value: { jobTitle: 1 } },
  { key: 'Job expiry', value: { endAt: 1 } },
];
